apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysql-pass
  literals:
  - password=redhat
resources:
  - wordpress-pod.yml
  - wordpress-svc.yml
  - wordpress-pvc.yml
  - mysql-pod.yml
  - mysql-pvc.yml
  - mysql-svc.yml